wordpress:
  build: .
  links:
    - database:mysql
  ports:
    - 8080:80
  volumes:
    - "./theme:/var/www/html/wp-content/themes/theme"
    - "./plugins:/var/www/html/wp-content/plugins"
    - "./uploads:/var/www/html/wp-content/uploads"

database:
  image: mysql
  volumes:
    - "./database:/var/lib/mysql"
  ports:
    - 3306:3306
  environment:
    MYSQL_ROOT_PASSWORD: example
